- src/KDFoundation/platform/win32/win32_platform_event_loop.cpp
- src/KDFoundation/platform/win32/win32_platform_event_loop.h
- src/KDGui/platform/win32/win32_platform_window.cpp
Functions passed as WNDPROC need to have their calling convention defined via CALLBACK define. Normally CALLBACK expands to __stdcall and by default functions are __cdecl which is a mismatch.
Not sure why it worked before.
Change-Id: I1bffcb7b9b4342375c5db631729a8deae357569f
> Fix compilation under certain circumstances

- cmake/dependencies.cmake
This fixes compilation errors on Windows with COM headers that define the 'interface' keyword.
> Bump KDBindings to 1.0.5

- cmake/dependencies.cmake
Fix external fmt version in find_package call to match that in the fetch_content call as a drive-by.
> Bump spdlog to 1.14.1

- tests/auto/utils/signal/tst_signal.cpp
Tests worked only if ran separately because CoreApplication was new'd
for each test but never deleted. This fired an assert that assures that
there's only one CoreApplication existing at a time
> Fix signal tests

- src/KDFoundation/platform/abstract_platform_event_loop.h
Lazy creation of ConnectionEvaluator in event loop was not guarded and
it may happen from a secondary thread (or multiple of those as was the
case with tests). This is actually quite probable as the idea behind
deferred connections is that they may be connected to from threads other
than main.
In "Multiple Signals with Evaluator" test two threads tried to do a deferred
connection at the same time and apparently this caused race condition in
creation of the evaluator.
Now we unconditionally create the connection evaluator in the event
loop. This way, we know that the evaluator is fully created by the end
of the event loop construction. Our assumption is that the user shouldn't
use the evaluator from another thread before the loop is fully
constructed.
> Fix race condition with deferred connections

- .clang-tidy
AnalyzeTemporaryDtors has been deprecated for a long time
> .clang-tidy - remove unsupported option 'AnalyzeTemporaryDtors'

- tests/auto/foundation/win32_platform_event_loop/tst_win32_platform_event_loop.cpp
It still fails sometimes so let's see what the logs will have to say with these additional debugs.
> Add debug messages to the win32 event loop test

- src/KDFoundation/CMakeLists.txt
- src/KDFoundation/platform/abstract_platform_event_loop.cpp
- src/KDFoundation/platform/abstract_platform_event_loop.h
- src/KDFoundation/platform/linux/linux_platform_event_loop.cpp
- src/KDFoundation/platform/linux/linux_platform_event_loop.h
- src/KDFoundation/platform/macos/macos_platform_event_loop.h
- src/KDFoundation/platform/macos/macos_platform_event_loop.mm
- src/KDFoundation/platform/win32/win32_platform_event_loop.cpp
- src/KDFoundation/platform/win32/win32_platform_event_loop.h
- src/KDGui/platform/android/android_platform_event_loop.cpp
- src/KDGui/platform/android/android_platform_event_loop.h
- src/KDGui/platform/linux/wayland/linux_wayland_platform_event_loop.cpp
- src/KDGui/platform/linux/wayland/linux_wayland_platform_event_loop.h
- src/KDGui/platform/linux/xcb/linux_xcb_platform_event_loop.cpp
- src/KDGui/platform/linux/xcb/linux_xcb_platform_event_loop.h
- tests/auto/utils/signal/tst_signal.cpp
Connection invocations are now evaluated automatically in the event loop. Any time an invocation is enqueued using the event loop's connection evaluator, the event loop is woken up.
This required a KDUtils-specific ConnectionEvaluator.
When given event loop is destroyed, it sets a reference in the evaluator to null. It's a defensive measure for the future to prevent misuse of lingering evaluators in case the user deletes the event loop first.
AbstractEventLoop::waitForEvents is not pure abstract anymore as it ensures evaluation of slot invocations.
Removed one copypasted comment in android event loop impl.
> Implement auto invocation of deferred slots

- .github/workflows/linters.yml
Rename nightly → linters as it better descrbies what it does, plus, we'll probably run it on pull requests later.
Fixed typo in matrix property name which prevented clang-tidy from running on Windows.
> Rename and fix workflow

- tests/auto/foundation/linux_platform_event_loop/tst_linux_platform_event_loop.cpp
Fixes this warning:
```
KDUtils/tests/auto/foundation/linux_platform_event_loop/tst_linux_platform_event_loop.cpp: In function ‘void DOCTEST_ANON_FUNC_38()’:
KDUtils/tests/auto/foundation/linux_platform_event_loop/tst_linux_platform_event_loop.cpp:402:11: warning: ignoring return value of ‘KDBindings::ConnectionHandle KDBindings::Signal<Args>::connect(const std::function<void(Args ...)>&) [with Args = {int}]’, declared with attribute ‘nodiscard’ [-Wunused-result]
402 |         });
|           ^
In file included from KDUtils/src/KDUtils/../KDFoundation/object.h:21,
from KDUtils/src/KDUtils/../KDFoundation/file_descriptor_notifier.h:14,
from KDUtils/src/KDUtils/../KDFoundation/platform/linux/linux_platform_event_loop.h:15,
from KDUtils/tests/auto/foundation/linux_platform_event_loop/tst_linu …
```
> Fix test compile warning

- src/KDGui/platform/linux/wayland/linux_wayland_platform_input.cpp
- src/KDGui/platform/linux/wayland/linux_wayland_platform_input.h
- src/KDGui/platform/linux/wayland/linux_wayland_platform_integration.cpp
- src/KDGui/platform/linux/wayland/linux_wayland_platform_integration.h
- src/KDGui/platform/linux/wayland/linux_wayland_platform_window.cpp
- src/KDGui/platform/linux/wayland/linux_wayland_platform_window.h
The event queue isn't always empty after closing a window. This caused a crash in some cases where the input handler tried to access a destroyed window.
Usual case:
```
virtual bool KDGui::LinuxWaylandPlatformWindow::destroy()                                 ← window closed
virtual KDGui::LinuxWaylandPlatformWindow::~LinuxWaylandPlatformWindow()                  ← platform window destroyed
void KDGui::LinuxWaylandPlatformInput::pointerLeave(wl_pointer*, uint32_t, wl_surface*)   ← sets m_pointer.accumulatedEvent.focus = nullptr
void KDGui::LinuxWaylandPlatformInput::pointerFrame(wl_pointer*)                          ← doesn't crash because m_pointer.accumulatedEvent.focus == nullptr
KDGui::LinuxWaylandPlatformInput::~LinuxWaylandPlatformInput()
void …
```
> wayland: guard accesses to PlatformWindow in PlatformInput

- .github/workflows/linters.yml
I think that nightly is not really needed if we have it for PRs. Plus
I left the manual dispatch so that we can start it as needed.
> Enable linters workflow on PRs and disable nightly

- .markdownlint.jsonc
- .mdlrc
- .mdlrc.rb
- .pre-commit-config.yaml
- .reuse/dep5
- README.md
It doesn't require Ruby and works out of the box on Windows. Original markdownlint wasn't able to install Ruby properly on Windows.
Fixed a newly found issue in README as well.
> Switch pre-commit to markdownlint-cli2

- tests/auto/foundation/win32_platform_event_loop/tst_win32_platform_event_loop.cpp
We should first join the server thread an only then do the WSACleanup() as closesocket() in server thread may be called after WSACleanup() if we don't join first.
> Fix win32 socket test

- cmake/dependencies.cmake
So that we will finally be able to use SingleShot connection and silence warnings on property signal connections.
> Update KDBinding Dependency to v1.1.0

- .clang-format
After pre-commit bumped our clang-format to 19.1.0 it started formatting some files differently (and incorrectly).
It turns out it's due to missing AttributeMacros config. Previous clang-format versions were more lenient about it.
See https://github.com/llvm/llvm-project/issues/94184 and https://github.com/KDAB/KDUtils/pull/37
> Fix formatting under clang-format >=19.1

- .github/workflows/build.yml
macOS 12 builder is getting decommissioned at GitHub [1] so let's build on the newer ones.
Changed action that downloads ninja to one compatible with macOS >=13.
Drive-By: Removed ancient Windows builder
[1] https://github.com/actions/runner-images/issues/10721
> Bump macOS builder version

- .github/workflows/build-external.yml
This is mostly about `fmt/spdlog` being a fast moving target breaking source-compat as they go along.
Added homebrew only, which has the latest versions, so is enough for good coverage.
Created separate .yml file as the main one is getting complex.
> ci: Add workflow to build against system 3rdparty

- .gitignore
- CMakePresets.json
- src/KDFoundation/CMakeLists.txt
- src/KDFoundation/platform/macos/macos_platform_event_loop.h
- src/KDFoundation/platform/macos/macos_platform_event_loop.mm
- src/KDFoundation/platform/macos/macos_platform_timer.h
- src/KDFoundation/platform/macos/macos_platform_timer.mm
- tests/auto/foundation/core_application/tst_core_application.cpp
Implements timer support for macOS platform.
Replaces PR #10 since I don't have access to the author's branch to amend stuff.
> macOS timers

- .github/workflows/dependency-bump.yml
requires manual trigger by the maintainer and supports:
- Printing current dependency versions (from FetchContent)
- Bumping individual dependencies to the proposed latest version
- Automatically creates a PR. Be sure to close and reopen these automatic PRs so that CI actually builds them (limitation of not using a PAT token)
> Add submodule-bump.yml

- .github/workflows/build.yml
Ubuntu 20.04 is out of support and GitHub Actions is removing the build container for it. If we truly need it, we need to setup a custom container I guess.
> remove ubuntu 20.04 build

- .github/workflows/build.yml
For now only the 24.04 one. If they are there, let's check on arm too.
> Add experimental Ubuntu Arm64 runner

- src/KDGui/platform/android/android_platform_event_loop.cpp
- src/KDGui/platform/android/android_platform_integration.cpp
- src/KDGui/platform/android/android_platform_integration.h
Track the status, position and times of the first touch event as equivalent to left mouse button clicks and drags.
Also use a more appropriate tag for logging.
Change-Id: I26fd55ec9f1c255661f4d89d81872d7c73a0c190
> Simple touchscreen mouse support for Android

- src/KDMqtt/mqtt.h
Adds missing macro `OPERATORS_FOR_FLAGS` for said enum.
> Enable operators for KDUtils::Flags<KDMqtt::MqttManager::ClientOptions>

- src/KDUtils/logging.cpp
In a non-console app on Windows, no logging is visible, so on that platform add the sink for output to the Visual Studio debug output pane.
Also remove unnecessary #ifdef, since the included headers have those.
> Add logging to OutputDebugString on Windows

- tests/CMakeLists.txt
- tests/auto/mqtt/CMakeLists.txt
- tests/auto/mqtt/tst_mqtt.cpp
Before we have pulled all of the FakeIt source code downloading a zip file via FetchContent.
This had two downsides:
- we only use a single header file from the sources so pulling all of the source code was a bit overkill
- using FetchConents lead to FakeIt files being installed when installing KDUtils library on Linux via `cmake --install . --prefix /path/to/prefix`
Now we download only the single header file we actually use. The new approach also avoids FakeIt files to be included when installing KDUtils library on Linux.
Fixes #60
> Download header only for FakeIt mocking framework

- tests/CMakeLists.txt
It's not available in any released version so we have to get the revision from dev. The changes since 2.4.11 up to this rev were minimal however so we should be safe.
> Use doctest revision compatible with CMake 4.0

- src/KDFoundation/destruction_helpers.h
Since connect is now [nodiscard]. Yet when connecting to a property's signal, we know there's no need to keep the connection handle around as long as the property remains valid.
Change-Id: Icd5124abc7c6bb28c5b81e7e047157b6abbb3dc4
> registerDestructionHelper: silence warnings KDBinding::Signal::connect

- src/KDFoundation/destruction_helpers.h
- tests/auto/foundation/CMakeLists.txt
- tests/auto/foundation/destruction_helper/CMakeLists.txt
- tests/auto/foundation/destruction_helper/tst_destruction_helper.cpp
Because headers should never have a using namespace declaration.
Also fix typos, add unit tests and minimal documentation.
Change-Id: Ic524c53417da7273c15c1c9eaa5f8ef8758340af
> destruction_helpers.h: remove using namespace KDBindings
